#!/usr/bin/env node
/**
 * Re-embeds every document with the currently configured embedding provider.
 *
 * Why this exists
 * ---------------
 * The AI layer's promise is that any OpenAI-spec provider swaps in through
 * configuration, without changing application code. That was true for chat and
 * *almost* true for embeddings: a model of a different width still needed a
 * hand-written migration, because `chunks.embedding` is a fixed-size
 * `vector(N)` column. Writing SQL is changing application code, so the promise
 * had an asterisk on it.
 *
 * What it cannot do is make the swap free. Vectors from two different models
 * are not comparable -- they are coordinates in unrelated spaces -- so every
 * stored embedding is worthless the moment the model changes, at *any* width.
 * Re-ingestion is therefore mandatory, not an optimisation. The honest goal is
 * not "zero steps" but "one command instead of hand-written SQL".
 *
 * Why it writes a migration rather than just running ALTER
 * --------------------------------------------------------
 * Migrations are the source of truth for this schema. An out-of-band ALTER
 * would be silently reverted by the next `pnpm db:reset`, leaving a database
 * whose column width disagrees with `.env` -- which the API then refuses to
 * boot against, far from the command that caused it. Generating a migration
 * keeps the change reproducible, reviewable and replayable on a teammate's
 * machine.
 *
 * Usage:
 *   pnpm reembed          # prompts before touching anything
 *   pnpm reembed --yes    # for CI and scripted runs
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const ok = (m) => console.log(`  \x1b[32m✓\x1b[0m ${m}`);
const info = (m) => console.log(`  \x1b[2m${m}\x1b[0m`);
const fail = (m, fix) => {
  console.error(`\n  \x1b[31m✗ ${m}\x1b[0m`);
  if (fix) console.error(`    ${fix}\n`);
  process.exit(1);
};

/** Reads `.env` without adding a dotenv dependency for one script. */
function readEnv() {
  const path = resolve(root, '.env');
  if (!existsSync(path)) fail('No .env found.', 'Run `pnpm bootstrap` first.');
  const out = {};
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line);
    if (m) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

/**
 * Runs a workspace binary directly.
 *
 * Not `pnpm exec`: shelling out to pnpm from a script pnpm launched makes
 * corepack try to install pnpm globally. Same reasoning as `setup.mjs`.
 */
function runLocal(bin, args) {
  const exe = resolve(root, 'node_modules', '.bin', bin);
  const r = spawnSync(exe, args, { cwd: root, stdio: 'inherit' });
  if (r.status !== 0) fail(`\`${bin} ${args.join(' ')}\` failed.`);
}

const env = readEnv();
const target = Number(env.AI_EMBEDDING_DIMENSIONS ?? 1536);
const provider = env.AI_EMBEDDING_PROVIDER ?? 'fake';
const model = env.AI_EMBEDDING_MODEL ?? '(default)';

if (!Number.isInteger(target) || target < 1) {
  fail(`AI_EMBEDDING_DIMENSIONS is "${env.AI_EMBEDDING_DIMENSIONS}", which is not a dimension.`);
}
if (target > 2000) {
  fail(
    `AI_EMBEDDING_DIMENSIONS is ${target}, above pgvector's 2000-dimension ceiling for HNSW ` +
      'on the `vector` type.',
    'Use a model that supports truncation, or migrate the column to `halfvec`.',
  );
}

console.log(`\nRe-embedding with \x1b[1m${provider}/${model}\x1b[0m at ${target} dimensions\n`);

console.log('  This will:');
console.log('    - delete every stored chunk and cached embedding');
console.log(`    - resize the vector columns to ${target} and rebuild the HNSW index`);
console.log('    - return every document to `queued` for re-ingestion');
console.log('');
info('Documents themselves are never touched. Only derived data is rebuilt.');
console.log('');

if (!process.argv.includes('--yes')) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const answer = await rl.question('  Continue? [y/N] ');
  rl.close();
  if (!/^y(es)?$/i.test(answer.trim())) {
    console.log('\n  Nothing changed.\n');
    process.exit(0);
  }
}

// A migration name is only unique per second; two runs in the same second
// would collide and the second would be skipped as already applied.
const stamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
const name = `${stamp}_reembed_${target}d.sql`;
const path = resolve(root, 'supabase', 'migrations', name);

writeFileSync(
  path,
  `-- ---------------------------------------------------------------------------
-- Re-embed at ${target} dimensions — generated by \`pnpm reembed\`.
--
-- Provider at generation time: ${provider}/${model}
--
-- Derived data only. Documents are the source of truth and are untouched; the
-- chunks and their vectors are rebuilt from them by the ingestion worker, which
-- picks up anything left in \`queued\` on its next start.
--
-- The deletes are not housekeeping, they are a precondition: pgvector cannot
-- change a column's width while rows of the old width are in it, and vectors
-- from a different model would be meaningless even if it could.
-- ---------------------------------------------------------------------------

-- Cached vectors are keyed by (content_hash, model), so a new model would never
-- read them -- but they still hold the old width, which blocks the ALTER below.
truncate table public.embedding_cache;

delete from public.chunks;

-- Rebuilt after the type change: an HNSW index is built for a specific width.
drop index if exists public.chunks_embedding_idx;

alter table public.chunks
  alter column embedding type extensions.vector(${target});

alter table public.embedding_cache
  alter column embedding type extensions.vector(${target});

create index chunks_embedding_idx on public.chunks
  using hnsw (embedding extensions.vector_cosine_ops);

-- \`content_hash\` must be cleared, not just the status: ingestion short-circuits
-- when the hash still matches, so a document left with its hash would be marked
-- ready again without a single vector being written.
update public.documents
   set status        = 'queued',
       content_hash  = null,
       chunk_count   = 0,
       error_message = null;
`,
  'utf8',
);

ok(`Wrote supabase/migrations/${name}`);

console.log('\nApplying migration\n');
runLocal('supabase', ['migration', 'up']);

console.log('');
ok('Schema resized and documents requeued');
console.log(`
  Restart the API to re-ingest:

    \x1b[1mpnpm dev\x1b[0m

  The worker enqueues everything left in \`queued\` on startup, so ingestion
  begins on its own. Watch progress on the Documents page.
`);
